-- ChessKidoo: import 50 students from Chesskidoo_Academy_Data_2026-06-08.xlsx
-- Idempotent: re-runnable (ON CONFLICT updates). Review before running in Supabase SQL editor.

INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-dinesh-sai-brother', 'DINESH(Sai brother)', 'student', '9789012394', 'Beginner', 800, '2026-06-06', '2026-06-10', 1600, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-sashwin', 'SASHWIN', 'student', '7373787875', 'Beginner', 800, '2026-06-05', '2026-06-11', 2700, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-moksha-pk', 'moksha pk', 'student', '9840514302', 'Beginner', 800, '2026-06-07', '2026-06-07', 2000, 'Paid', 'Paid', 'Group', 'Group', '17:00', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-poornima-parents', 'POORNIMA - PARENTS', 'student', '9626846669', 'Beginner', 800, '2026-06-07', '2026-07-07', 1900, 'Due', 'Due', 'Group', 'Group', '17:00', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-rohith-expenditure-chess-academy', 'Rohith Expenditure chess Academy', 'student', '6385688722', 'Beginner', 800, '2026-06-01', '2026-06-07', 1000, 'Not Enrolled', 'Not Enrolled', 'Group', 'Group', '17:00', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-aradhya', 'Aradhya', 'student', '41872621', 'Beginner', 800, '2026-06-01', '2026-06-28', 2900, 'Not Enrolled', 'Not Enrolled', 'Group', 'Group', '17:00', 'VASANTH KUMAR')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-samiksha', 'SAMIKSHA', 'student', '9003457873', 'Beginner', 800, '2026-05-29', '2026-06-29', 4800, 'Paid', 'Paid', 'Group', 'Group', '17:00', 'ROHITH SELVARAJ')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-venkatesh-laxminagar-daughter', 'VENKATESH LAXMINAGAR -daughter', 'student', '9686103333', 'Beginner', 800, '2026-06-05', '2026-06-10', 2500, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-venkatesh-laxminagar-son', 'VENKATESH LAXMINAGAR -SON', 'student', '9686103333', 'Beginner', 800, '2026-06-07', '2026-06-10', 1800, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-ilam-bharathi', 'ILAM BHARATHI', 'student', '9629673733', 'Beginner', 800, '2026-06-10', '2026-06-15', 1600, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'RANJITH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-yadhuiver', 'YADHUIVER', 'student', '9551118111', 'Beginner', 800, '2026-06-03', '2026-06-03', 2700, 'Paid', 'Paid', 'Group', 'Group', '17:00', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-yogesh', 'YOGESH', 'student', '9344097252', 'Beginner', 800, '2026-06-03', '2026-06-03', 2600, 'Paid', 'Paid', 'Group', 'Group', '17:00', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-abinitha', 'ABINITHA', 'student', '9952209603', 'Beginner', 800, '2026-06-01', '2026-06-02', 2600, 'Due', 'Due', 'Group', 'Group', '17:00', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-yuvan', 'YUVAN', 'student', '9789107123', 'Beginner', 800, '2026-06-01', '2026-06-03', 2800, 'Due', 'Due', 'Group', 'Group', '17:00', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-banu-priya', 'BANU PRIYA', 'student', '9080578952', 'Beginner', 800, '2026-05-18', '2026-06-18', 1000, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-saranya-offline-academy', 'Saranya--offline academy', 'student', '8220165338', 'Beginner', 800, '2026-05-18', '2026-06-20', 1270, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-prajesh-offline-academy', 'Prajesh --offline academy', 'student', '9442628925', 'Beginner', 800, '2026-05-18', '2026-06-19', 1270, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-mansa-offline-academy', 'Mansa --offline academy', 'student', '8667593451', 'Beginner', 800, '2026-05-18', '2026-06-17', 1270, 'Pending', 'Pending', 'Group', 'Group', '17:00', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-sai', 'SAI', 'student', '9789012394', 'Beginner', 800, '2026-05-07', '2026-06-07', 1600, 'Due', 'Due', 'Group', 'Group', '17:00', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-mohammed-aakif', 'MOHAMMED AAKIF', 'student', '9566439055', 'Beginner', 800, '2026-04-20', '2026-06-20', 1700, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'SUDHIN')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-pranish-p', 'PRANISH P', 'student', '9942827234', 'Beginner', 800, '2026-04-27', '2026-06-04', 1500, 'Paid', 'Paid', 'Group', 'Group', 'Weekend', 'SUDHIN')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-susin', 'SUSIN', 'student', '8667258857', 'Advanced', 800, '2026-04-08', '2026-06-08', 1800, 'Paid', 'Paid', 'Group', 'Group', 'Weekend', 'RANJITH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-atish-vidun', 'ATISH VIDUN', 'student', '9677751414', 'Beginner', 800, '2026-04-24', '2026-06-04', 3200, 'Paid', 'Paid', 'Single', 'Single', 'Weekend', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-balaji-ganesh', 'BALAJI GANESH', 'student', '7324276741', 'Beginner', 800, '2026-02-21', '2026-06-06', 5200, 'Paid', 'Paid', 'Group', 'Group', 'Weekday', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-athivik', 'ATHIVIK', 'student', '8608969999', 'Beginner', 800, '2026-04-24', '2026-06-14', 2500, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-sachin', 'SACHIN', 'student', '9944227799', 'Advanced', 800, '2026-04-24', '2026-06-04', 3000, 'Not Enrolled', 'Not Enrolled', 'Group', 'Group', 'Weekend', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-uttasan', 'UTTASAN', 'student', '8870897095', 'Advanced', 800, '2026-04-24', '2026-06-04', 3000, 'Paid', 'Paid', 'Single', 'Single', 'Weekend', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-prnavav', 'PRNAVAV', 'student', '9843431086', 'Beginner', 800, '2026-04-08', '2026-06-08', 2200, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-shrevin', 'SHREVIN', 'student', '7899295230', 'Beginner', 800, '2026-03-13', '2026-06-25', 1800, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-aara-v', 'AARA V', 'student', '9786767007', 'Beginner', 800, '2026-04-24', '2026-06-04', 1800, 'Paid', 'Paid', 'Group', 'Group', 'Weekend', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-rakistha', 'RAKISTHA', 'student', '9789779973', 'Beginner', 800, '2026-04-24', '2026-06-27', 800, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-nigunan', 'NIGUNAN', 'student', '9952178004', 'Beginner', 800, '2026-04-10', '2026-06-10', 2400, 'Pending', 'Pending', 'Single', 'Single', 'Weekday', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-sreelaxmi', 'SREELAXMI', 'student', '9952178004', 'Beginner', 800, '2026-04-24', '2026-06-04', 5000, 'Paid', 'Paid', 'Group', 'Group', 'Morning & Evening', 'ROHITH SELVARAJ')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-magathi', 'MAGATHI', 'student', '9843431086', 'Beginner', 800, '2026-04-08', '2026-06-08', 2200, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-krishna', 'KRISHNA', 'student', '8300854984', 'Intermediate', 800, '2026-04-24', '2026-06-21', 750, 'Pending', 'Pending', 'Group', 'Group', 'Morning & Evening', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-velava', 'VELAVA', 'student', '9025589784', 'Intermediate', 800, '2026-04-24', '2026-06-25', 1800, 'Paid', 'Paid', 'Group', 'Group', 'Fri & Sat', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-mukilan', 'MUKILAN', 'student', '8300074400', 'Advanced', 800, '2026-04-24', '2026-06-04', 2600, 'Paid', 'Paid', 'Group', 'Group', 'Fri & Sat', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-anfal', 'ANFAL', 'student', '8870846140', 'Intermediate', 800, '2026-04-24', '2026-06-22', 3300, 'Pending', 'Pending', 'Group', 'Group', 'Fri & Sat', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-anukshaa', 'ANUKSHAA', 'student', '6374838638', 'Beginner', 800, '2026-04-23', '2026-06-23', 1800, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-varun', 'VARUN', 'student', '9677499903', 'Beginner', 1400, '2026-03-15', '2026-06-15', 1600, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'RANJITH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-sakunthala', 'SAKUNTHALA', 'student', '9150417754', 'Beginner', 800, '2026-04-15', '2026-06-04', 1700, 'Not Enrolled', 'Not Enrolled', 'Group', 'Group', 'Weekend', 'SUDHIN')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-sakthi-sathya-sankarlingam', 'SAKTHI - SATHYA -SANKARLINGAM', 'student', '426045111', 'Elite', 799, '2026-04-15', '2026-06-12', 7000, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'RANJITH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-riyas', 'RIYAS', 'student', '9677499903', 'Beginner', 1400, '2026-03-15', '2026-06-15', 1600, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'RANJITH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-poonthalir', 'POONTHALIR', 'student', '9952484616', 'Beginner', 1000, '2026-03-22', '2026-06-21', 900, 'Pending', 'Pending', 'Group', 'Group', 'Morning & Evening', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-mohammed-rayan', 'MOHAMMED RAYAN', 'student', '9566439055', 'Beginner', 800, '2026-04-13', '2026-06-20', 1700, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-jayaraj', 'JAYARAJ', 'student', '8682837002', 'Beginner', 1000, '2026-03-07', '2026-06-20', 2500, 'Pending', 'Pending', 'Group', 'Group', 'Fri & Sat', 'VISHNU')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-jeevan-basic', 'JEEVAN BASIC', 'student', '4086792841', 'Beginner', 800, '2026-03-15', '2026-06-27', 3300, 'Pending', 'Pending', 'Group', 'Group', 'Weekday', 'YOGESH')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-arunya', 'ARUNYA', 'student', '9042040150', 'Beginner', 800, '2026-04-24', '2026-06-24', 2400, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-aadhavan-singapore', 'AADHAVAN - SINGAPORE', 'student', '86501029', 'Beginner', 850, '2026-04-20', '2026-06-04', 2200, 'Paid', 'Paid', 'Group', 'Group', 'Weekday', 'ARIVUSELVAM')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;
INSERT INTO users (id, full_name, role, phone_number, level, rating, join_date, due_date, fee, payment_status, status, session_type, session, schedule, coach) VALUES ('xl-anush', 'ANUSH', 'student', '6374838638', 'Intermediate', 800, '2026-04-23', '2026-06-23', 1000, 'Pending', 'Pending', 'Group', 'Group', 'Weekend', 'GYANASURYA')
  ON CONFLICT (id) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, phone_number=EXCLUDED.phone_number, level=EXCLUDED.level, rating=EXCLUDED.rating, join_date=EXCLUDED.join_date, due_date=EXCLUDED.due_date, fee=EXCLUDED.fee, payment_status=EXCLUDED.payment_status, status=EXCLUDED.status, session_type=EXCLUDED.session_type, session=EXCLUDED.session, schedule=EXCLUDED.schedule, coach=EXCLUDED.coach;