-- ==============================================================================
-- ChessKidoo Supabase Complete Schema
-- Copy and paste this entire script into your Supabase SQL Editor and run it.
-- This will create all the necessary tables for the frontend to work perfectly.
-- ==============================================================================

-- 1. USERS TABLE
-- Stores students, coaches, admins, and parents.
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    userid TEXT,
    email TEXT,
    full_name TEXT,
    role TEXT,
    phone_number TEXT,
    city TEXT,
    level TEXT,
    rating INTEGER DEFAULT 800,
    coach TEXT,
    batch TEXT,
    session TEXT,
    schedule TEXT,
    fee TEXT,
    status TEXT,
    due_date TEXT,
    join_date TEXT,
    age INTEGER,
    grade TEXT,
    puzzle INTEGER DEFAULT 0,
    game INTEGER DEFAULT 0,
    star INTEGER DEFAULT 0,
    photo TEXT,
    certificate TEXT,
    last_note TEXT,
    childEmail TEXT, -- Used for parent accounts
    timetable TEXT, -- Used for coaches
    revenue TEXT,   -- Used for coaches
    classes INTEGER, -- Used for coaches
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. EXPENSES TABLE
-- Tracks academy expenditures.
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TEXT,
    category TEXT,
    description TEXT,
    amount TEXT,
    mode TEXT,
    bill TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. DOCUMENT TABLE
-- Stores uploaded documents and class files.
CREATE TABLE IF NOT EXISTS public.document (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_name TEXT,
    name TEXT,
    level TEXT,
    coach TEXT,
    batch TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. ATTENDANCE TABLE
-- Tracks daily attendance for students.
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid TEXT,
    "studentId" TEXT,
    "studentName" TEXT,
    "classId" TEXT,
    "className" TEXT,
    "coachId" TEXT,
    "markedAt" TIMESTAMPTZ,
    date TEXT,
    status TEXT,
    class_title TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Add columns to existing attendance table if upgrading
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "studentId" TEXT;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "studentName" TEXT;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "classId" TEXT;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "className" TEXT;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "coachId" TEXT;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "markedAt" TIMESTAMPTZ;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS class_title TEXT;

-- 5. RATINGS TABLE
-- Tracks ELO rating history over time for students.
CREATE TABLE IF NOT EXISTS public.ratings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    online INTEGER,
    international INTEGER,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TOUR RATINGS TABLE
-- Tracks tournament results and rating changes.
CREATE TABLE IF NOT EXISTS public.tourRatings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    name TEXT,
    result TEXT,
    change TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. RESOURCES TABLE
-- Tracks homework, class notes, and puzzles.
CREATE TABLE IF NOT EXISTS public.resources (
    id TEXT PRIMARY KEY,
    name TEXT,
    type TEXT,
    level TEXT,
    notes TEXT,
    link TEXT,
    coach TEXT,
    batch TEXT,
    fen TEXT,
    solution TEXT,
    difficulty TEXT,
    category TEXT,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. MEETINGS TABLE
-- Tracks scheduled online classes and Google Meet links.
CREATE TABLE IF NOT EXISTS public.meetings (
    id TEXT PRIMARY KEY,
    date TEXT,
    time TEXT,
    coach TEXT,
    coachId TEXT,
    coachName TEXT,
    title TEXT,
    batch TEXT,
    duration INTEGER,
    link TEXT,
    notes TEXT,
    type TEXT,
    studentIds TEXT[], -- ARRAY of student UUIDs
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. LEADS TABLE
-- Tracks "Book a Free Demo" form submissions.
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    phone TEXT,
    parent_name TEXT,
    child_age TEXT,
    city TEXT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. COACH NOTES TABLE
-- Stores feedback notes from coaches to students.
CREATE TABLE IF NOT EXISTS public.coach_notes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student TEXT,
    coach TEXT,
    text TEXT,
    date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. CREDENTIALS TABLE
-- Stores custom passwords for the mock-auth system.
CREATE TABLE IF NOT EXISTS public.credentials (
    email TEXT PRIMARY KEY,
    password TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. BATCH LINKS TABLE
-- Stores Google Meet links for each batch level.
CREATE TABLE IF NOT EXISTS public.batch_links (
    batch_level TEXT PRIMARY KEY,
    link TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. CLASSES TABLE
-- Stores structured class schedules.
CREATE TABLE IF NOT EXISTS public.classes (
    id TEXT PRIMARY KEY,
    coachId TEXT,
    coachName TEXT,
    title TEXT,
    level TEXT,
    batch TEXT,
    days TEXT[], -- ARRAY of days like ['Mon', 'Thu']
    time TEXT,
    duration INTEGER,
    zoomLink TEXT,
    max_students INTEGER DEFAULT 10,
    studentIds TEXT[], -- ARRAY of student IDs
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 14. MONTHLY REPORTS TABLE
-- Tracks monthly performance reports for students.
CREATE TABLE IF NOT EXISTS public.monthly_reports (
    id TEXT PRIMARY KEY,
    studentId TEXT,
    studentName TEXT,
    coachId TEXT,
    coachName TEXT,
    month INTEGER,
    year INTEGER,
    attendance INTEGER,
    puzzles INTEGER,
    notes TEXT,
    recommendation TEXT,
    topics TEXT,
    rating INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 15. PUZZLE SCORES TABLE
-- Tracks puzzle solving history and XP for leaderboard.
CREATE TABLE IF NOT EXISTS public.puzzle_scores (
    id TEXT PRIMARY KEY,
    userId TEXT,
    userName TEXT,
    puzzleId TEXT,
    solved BOOLEAN,
    time INTEGER,
    mistakes INTEGER,
    xp INTEGER,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 16. COACH ATTENDANCE TABLE
-- Tracks when coaches join their own classes.
CREATE TABLE IF NOT EXISTS public.coach_attendance (
    id TEXT PRIMARY KEY,
    coachId TEXT,
    classId TEXT,
    date TEXT,
    joinedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 17. ASSIGNMENTS TABLE
-- Stores homework tasks given by coaches to students.
CREATE TABLE IF NOT EXISTS public.assignments (
    id TEXT PRIMARY KEY,
    title TEXT,
    pgn TEXT,
    type TEXT, -- 'study', 'guess', 'practice'
    assignedTo TEXT, -- 'all' or batch name
    dueDate TEXT,
    description TEXT,
    coach TEXT,
    moves INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 18. HW SUBMISSIONS TABLE
-- Tracks student completion of homework assignments.
CREATE TABLE IF NOT EXISTS public.hw_submissions (
    id TEXT PRIMARY KEY,
    assignment_id TEXT,
    student_id TEXT,
    accuracy INTEGER,
    movesStudied INTEGER,
    totalMoves INTEGER,
    note TEXT,
    completed BOOLEAN DEFAULT true,
    submittedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 19. FEEDBACK TABLE
-- Stores feedback from parents to the academy.
CREATE TABLE IF NOT EXISTS public.feedback (
    id TEXT PRIMARY KEY,
    fromId TEXT,
    fromName TEXT,
    fromRole TEXT,
    childId TEXT,
    childName TEXT,
    toId TEXT,
    toName TEXT,
    message TEXT,
    rating INTEGER,
    category TEXT,
    replied BOOLEAN DEFAULT false,
    reply TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- SCHEMA ADDITIONS — Run these if you already have the tables created above.
-- These are safe to re-run (uses ADD COLUMN IF NOT EXISTS).
-- ==============================================================================

-- Streak tracking columns on users
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS streak_count INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS streak_last_date TEXT;

-- Spaced Repetition System data (JSON string, per student)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS srs_data TEXT;

-- ==============================================================================
-- SECURITY & ACCESS POLICIES
-- RLS is ENABLED on all tables. Access is governed by the policies in
-- supabase/rls.sql — run that file in the SQL editor AFTER this one.
-- The authenticated role is granted DML; anon gets only what RLS allows.
-- ==============================================================================

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tourRatings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batch_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.puzzle_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hw_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- Grant table-level DML to authenticated role (RLS policies restrict further)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.users TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.expenses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.document TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.attendance TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.ratings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tourRatings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.resources TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.meetings TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.leads TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.coach_notes TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.credentials TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.batch_links TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.classes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monthly_reports TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.puzzle_scores TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.coach_attendance TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.assignments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.hw_submissions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.feedback TO authenticated;

-- Grant sequence usage for auto-increment columns
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ==============================================================================
-- DATA INTEGRITY — Unique constraints
-- ==============================================================================

-- Prevent duplicate attendance records for the same student on the same date
ALTER TABLE public.attendance
  DROP CONSTRAINT IF EXISTS uq_attendance_user_date;
ALTER TABLE public.attendance
  ADD CONSTRAINT uq_attendance_user_date UNIQUE (userid, date);

-- IMPORTANT: After running this file, run supabase/rls.sql to apply all
-- Row Level Security policies. The two files must both be applied.

-- ==============================================================================
-- 10. STORAGE BUCKET: DOCUMENTS
-- The admin portal uploads student certificates to this bucket.
-- ==============================================================================

-- Create the 'documents' storage bucket and make it public
INSERT INTO storage.buckets (id, name, public) 
VALUES ('documents', 'documents', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Explicitly drop existing policies to avoid conflict errors when rerunning
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Allow Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow Deletes" ON storage.objects;

-- Allow public read access to all files in the documents bucket
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'documents');

-- Allow anon/authenticated users to upload files
CREATE POLICY "Allow Uploads" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'documents');

-- Allow anon/authenticated users to delete files
CREATE POLICY "Allow Deletes" 
ON storage.objects FOR DELETE 
USING (bucket_id = 'documents');
