-- ==============================================================================
-- ChessKidoo Complete Supabase Rebuild & Setup Script
-- ==============================================================================
-- INSTRUCTIONS:
-- 1. To start completely fresh, UNCOMMENT the "DROP TABLES" block directly below
--    by removing the /* and */ symbols. This will wipe out all existing data.
-- 2. Copy and paste this entire script into your Supabase Dashboard SQL Editor.
-- 3. Click the "Run" button to execute and build your schema.
-- ==============================================================================

-- ── UNCOMMENT BELOW TO WIPE ALL TABLES AND START FRESH ────────────────────────
/*
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.document CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.ratings CASCADE;
DROP TABLE IF EXISTS public.tourRatings CASCADE;
DROP TABLE IF EXISTS public.resources CASCADE;
DROP TABLE IF EXISTS public.meetings CASCADE;
DROP TABLE IF EXISTS public.leads CASCADE;
DROP TABLE IF EXISTS public.coach_notes CASCADE;
DROP TABLE IF EXISTS public.credentials CASCADE;
DROP TABLE IF EXISTS public.batch_links CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.monthly_reports CASCADE;
DROP TABLE IF EXISTS public.puzzle_scores CASCADE;
DROP TABLE IF EXISTS public.coach_attendance CASCADE;
DROP TABLE IF EXISTS public.assignments CASCADE;
DROP TABLE IF EXISTS public.hw_submissions CASCADE;
DROP TABLE IF EXISTS public.feedback CASCADE;
DROP TABLE IF EXISTS public.broadcasts CASCADE;
*/

-- ── 1. USERS TABLE ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    userid TEXT,
    email TEXT,
    full_name TEXT,
    role TEXT,
    phone_number TEXT,
    city TEXT,
    level TEXT,
    rating INTEGER DEFAULT 800,
    coach TEXT,
    batch TEXT,
    session TEXT,
    schedule TEXT,
    fee TEXT,
    status TEXT,
    due_date TEXT,
    join_date TEXT,
    age INTEGER,
    grade TEXT,
    puzzle INTEGER DEFAULT 0,
    game INTEGER DEFAULT 0,
    star INTEGER DEFAULT 0,
    photo TEXT,
    certificate TEXT,
    last_note TEXT,
    "childEmail" TEXT,
    timetable TEXT,
    revenue TEXT,
    classes INTEGER DEFAULT 0,
    streak_count INTEGER DEFAULT 0,
    streak_last_date TEXT,
    srs_data JSONB,
    session_type TEXT, -- legacy support
    payment_status TEXT, -- legacy support
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 2. EXPENSES TABLE ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TEXT,
    category TEXT,
    description TEXT,
    amount TEXT,
    mode TEXT,
    bill TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 3. DOCUMENT TABLE ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.document (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_name TEXT,
    name TEXT,
    level TEXT,
    coach TEXT,
    link TEXT,
    batch TEXT,
    user_ids TEXT,
    type TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 4. ATTENDANCE TABLE ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid TEXT,
    "studentId" TEXT,
    "studentName" TEXT,
    "classId" TEXT,
    "className" TEXT,
    "coachId" TEXT,
    "markedAt" TIMESTAMPTZ,
    date TEXT,
    status TEXT,
    class_title TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uq_attendance_user_date UNIQUE (userid, date)
);

-- ── 5. RATINGS TABLE ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ratings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    online INTEGER,
    international INTEGER,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 6. TOUR RATINGS TABLE ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tourRatings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    name TEXT,
    result TEXT,
    change TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 7. RESOURCES TABLE ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.resources (
    id TEXT PRIMARY KEY,
    name TEXT,
    type TEXT,
    level TEXT,
    notes TEXT,
    link TEXT,
    coach TEXT,
    batch TEXT,
    fen TEXT,
    solution TEXT,
    difficulty TEXT,
    category TEXT,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 8. MEETINGS TABLE ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.meetings (
    id TEXT PRIMARY KEY,
    date TEXT,
    time TEXT,
    coach TEXT,
    "coachId" TEXT,
    "coachName" TEXT,
    title TEXT,
    batch TEXT,
    duration INTEGER,
    link TEXT,
    notes TEXT,
    type TEXT,
    "studentIds" TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 9. LEADS TABLE ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    phone TEXT,
    parent_name TEXT,
    child_age TEXT,
    city TEXT,
    status TEXT,
    email TEXT,
    message TEXT,
    source TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    full_name TEXT, -- legacy support
    age TEXT -- legacy support
);

-- ── 10. COACH NOTES TABLE ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.coach_notes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student TEXT,
    coach TEXT,
    text TEXT,
    date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 11. CREDENTIALS TABLE ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.credentials (
    email TEXT PRIMARY KEY,
    password TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 12. BATCH LINKS TABLE ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.batch_links (
    batch_level TEXT PRIMARY KEY,
    link TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 13. CLASSES TABLE ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.classes (
    id TEXT PRIMARY KEY,
    "coachId" TEXT,
    "coachName" TEXT,
    title TEXT,
    level TEXT,
    batch TEXT,
    days TEXT[],
    time TEXT,
    duration INTEGER,
    zoomLink TEXT,
    max_students INTEGER DEFAULT 10,
    "studentIds" TEXT[],
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    students INTEGER, -- legacy support
    max INTEGER, -- legacy support
    coach TEXT, -- legacy support
    schedule TEXT -- legacy support
);

-- ── 14. MONTHLY REPORTS TABLE ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.monthly_reports (
    id TEXT PRIMARY KEY,
    "studentId" TEXT,
    "studentName" TEXT,
    "coachId" TEXT,
    "coachName" TEXT,
    month INTEGER,
    year INTEGER,
    attendance INTEGER,
    puzzles INTEGER,
    notes TEXT,
    recommendation TEXT,
    topics TEXT[],
    rating INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 15. PUZZLE SCORES TABLE ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.puzzle_scores (
    id TEXT PRIMARY KEY,
    "userId" TEXT,
    "userName" TEXT,
    "puzzleId" TEXT,
    solved BOOLEAN,
    time INTEGER,
    mistakes INTEGER,
    xp INTEGER,
    date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 16. COACH ATTENDANCE TABLE ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.coach_attendance (
    id TEXT PRIMARY KEY,
    "coachId" TEXT,
    "classId" TEXT,
    date TEXT,
    "joinedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 17. ASSIGNMENTS TABLE ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.assignments (
    id TEXT PRIMARY KEY,
    title TEXT,
    pgn TEXT,
    type TEXT,
    "assignedTo" TEXT[],
    "dueDate" TEXT,
    description TEXT,
    coach TEXT,
    moves JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 18. HW SUBMISSIONS TABLE ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.hw_submissions (
    id TEXT PRIMARY KEY,
    assignment_id TEXT,
    student_id TEXT,
    accuracy INTEGER,
    "movesStudied" INTEGER,
    "totalMoves" INTEGER,
    note TEXT,
    completed BOOLEAN DEFAULT false,
    "submittedAt" TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 19. FEEDBACK TABLE ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.feedback (
    id TEXT PRIMARY KEY,
    "fromId" TEXT,
    "fromName" TEXT,
    "fromRole" TEXT,
    "childId" TEXT,
    "childName" TEXT,
    "toId" TEXT,
    "toName" TEXT,
    message TEXT,
    rating INTEGER,
    category TEXT,
    replied BOOLEAN DEFAULT false,
    reply TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 20. BROADCASTS TABLE ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.broadcasts (
    id TEXT PRIMARY KEY,
    fen TEXT,
    pgn TEXT,
    coach TEXT,
    ts BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- SEED DATA SETUP (Optional - Safe for Re-runs)
-- ==============================================================================

-- ── Admin and Coaches ─────────────────────────────────────────────────────────
INSERT INTO public.users (id, userid, email, full_name, role, rating, classes, created_at)
VALUES
  ('a007b0b0-9b30-478f-a147-1af18dff20ce', 'admin-root', 'admin@chesskidoo.com', 'Academy Admin', 'admin', NULL, 0, NOW()),
  ('c1', 'c_arivuselevam', 'arivuselvam@chesskidoo.com', 'ARIVUSELVAM', 'coach', 1500, 0, NOW()),
  ('c2', 'c_vishnu',      'vishnu@chesskidoo.com',      'VISHNU',       'coach', 1600, 0, NOW()),
  ('c3', 'c_gyanasurya',  'gyanasurya@chesskidoo.com',  'GYANASURYA',   'coach', 1550, 0, NOW()),
  ('c4', 'c_yogesh',      'yogesh@chesskidoo.com',      'YOGESH',       'coach', 1620, 0, NOW()),
  ('c5', 'c_rohit',       'rohit@chesskidoo.com',       'ROHIT',        'coach', 1500, 0, NOW())
ON CONFLICT (id) DO NOTHING;

-- ── Default Offline Credentials for Login Fallback (Pre-hashed SHA-256) ────────
INSERT INTO public.credentials (email, password, created_at)
VALUES
  ('admin@chesskidoo.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', NOW()),
  ('admin@gmail.com',      '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', NOW()),
  ('arivuselvam@chesskidoo.com', '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('vishnu@chesskidoo.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('gyanasurya@chesskidoo.com',  '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('yogesh@chesskidoo.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('rohit@chesskidoo.com',       '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW())
ON CONFLICT (email) DO NOTHING;

-- ── Sample Students ───────────────────────────────────────────────────────────
INSERT INTO public.users 
  (id, email, full_name, role, level, rating, coach, batch, session, schedule, fee, status, due_date, join_date)
VALUES
  ('s1',  'aadhavan@chesskidoo.com', 'AADHAVAN - SINGAPORE', 'student', 'Beginner',     850, 'ARIVUSELVAM',  'Evening',  'Group', '17:00',           '2200',  'Paid',    '04-May-2026', '2026-04-20'),
  ('s2',  'aarav@chesskidoo.com',    'AARA V',               'student', 'Beginner',     800, 'GYANASURYA',   'Weekend',  'Group', 'WEEKEND',         '1800',  'Paid',    '14-May-2026', '2026-04-24'),
  ('s3',  'anfal@chesskidoo.com',    'ANFAL',                'student', 'Intermediate', 800, 'VISHNU',       'Evening',  'Group', 'FRI & SAT',       '3300',  'Paid',    '20-May-2026', '2026-04-24'),
  ('s4',  'anushya@chesskidoo.com',  'ANUSHYA',              'student', 'Beginner',     800, 'ARIVUSELVAM',  'Evening',  'Group', '17:00',           '1800',  'Pending', '18-May-2026', '2026-04-23')
ON CONFLICT (id) DO NOTHING;

-- ==============================================================================
-- DATABASE SECURITY & API ACCESS (RLS BYPASS)
-- ==============================================================================
-- Enables public API reads/writes so the client app does not get blocked by policies.

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.document DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tourRatings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.batch_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.puzzle_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.hw_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcasts DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.users TO anon, authenticated;
GRANT ALL ON TABLE public.expenses TO anon, authenticated;
GRANT ALL ON TABLE public.document TO anon, authenticated;
GRANT ALL ON TABLE public.attendance TO anon, authenticated;
GRANT ALL ON TABLE public.ratings TO anon, authenticated;
GRANT ALL ON TABLE public.tourRatings TO anon, authenticated;
GRANT ALL ON TABLE public.resources TO anon, authenticated;
GRANT ALL ON TABLE public.meetings TO anon, authenticated;
GRANT ALL ON TABLE public.leads TO anon, authenticated;
GRANT ALL ON TABLE public.coach_notes TO anon, authenticated;
GRANT ALL ON TABLE public.credentials TO anon, authenticated;
GRANT ALL ON TABLE public.batch_links TO anon, authenticated;
GRANT ALL ON TABLE public.classes TO anon, authenticated;
GRANT ALL ON TABLE public.monthly_reports TO anon, authenticated;
GRANT ALL ON TABLE public.puzzle_scores TO anon, authenticated;
GRANT ALL ON TABLE public.coach_attendance TO anon, authenticated;
GRANT ALL ON TABLE public.assignments TO anon, authenticated;
GRANT ALL ON TABLE public.hw_submissions TO anon, authenticated;
GRANT ALL ON TABLE public.feedback TO anon, authenticated;
GRANT ALL ON TABLE public.broadcasts TO anon, authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- ==============================================================================
-- STORAGE BUCKETS SETUP (For file uploads & attachments)
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public) 
VALUES ('documents', 'documents', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Allow Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow Deletes" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'documents');
CREATE POLICY "Allow Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'documents');
CREATE POLICY "Allow Deletes" ON storage.objects FOR DELETE USING (bucket_id = 'documents');
