-- ============================================================================
--  ChessKidoo — Hybrid PGN Vault  (Supabase migration)
--  Run this in the Supabase SQL editor (or `supabase db push`).
--
--  Design: local-first + cloud. The frontend (pgn-vault.js) works entirely
--  from localStorage when these tables are absent, and transparently syncs
--  to Supabase once this migration is applied — mirroring the existing
--  `student_games` pattern in db.js (tableLive / graceful fallback).
--
--  Tables
--    pgn_games           — the vault: every saved game + metadata
--    pgn_analysis        — Stockfish results, one row per analysed game
--    pgn_analysis_queue  — background job queue consumed by the edge function
--    pgn_notes           — per-position coach / student annotations
--  Storage
--    bucket "pgns"       — optional raw .pgn blobs
-- ============================================================================

-- ── 1. VAULT: pgn_games ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pgn_games (
    id           TEXT PRIMARY KEY,                 -- app-generated e.g. 'pgn-<ts>-<rand>'
    user_id      TEXT,                             -- owner (users.userid / users.id)
    source       TEXT DEFAULT 'upload',            -- upload | manual | lichess | chesscom | tournament | coach | class
    white        TEXT,
    black        TEXT,
    white_elo    INTEGER,
    black_elo    INTEGER,
    my_color     TEXT,                             -- 'white' | 'black' | null
    result       TEXT,                             -- '1-0' | '0-1' | '1/2-1/2' | '*'
    outcome      TEXT,                             -- 'win' | 'loss' | 'draw' | 'unknown'  (from my_color)
    opening      TEXT,
    eco          TEXT,
    event        TEXT,
    site         TEXT,
    game_date    TEXT,
    time_control TEXT,
    time_class   TEXT,                             -- bullet | blitz | rapid | classical | online
    ply          INTEGER DEFAULT 0,
    accuracy     NUMERIC,                          -- 0-100, may be filled by analysis
    fen          TEXT,                             -- final position
    pgn          TEXT NOT NULL,
    tags         JSONB DEFAULT '[]'::jsonb,        -- ['blunder','homework','favourite', ...]
    analysed     BOOLEAN DEFAULT FALSE,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pgn_games_user    ON public.pgn_games (user_id);
CREATE INDEX IF NOT EXISTS idx_pgn_games_source  ON public.pgn_games (source);
CREATE INDEX IF NOT EXISTS idx_pgn_games_opening ON public.pgn_games (opening);
CREATE INDEX IF NOT EXISTS idx_pgn_games_result  ON public.pgn_games (result);
CREATE INDEX IF NOT EXISTS idx_pgn_games_created ON public.pgn_games (created_at DESC);

-- ── 2. ANALYSIS RESULTS: pgn_analysis ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pgn_analysis (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id     TEXT REFERENCES public.pgn_games(id) ON DELETE CASCADE,
    user_id     TEXT,
    engine      TEXT DEFAULT 'stockfish',
    depth       INTEGER,
    summary     JSONB,        -- { accuracy, acpl, blunders, mistakes, inaccuracies, eval_cp, best_move }
    moves       JSONB,        -- [{ ply, san, eval_cp, best, judgement }]
    status      TEXT DEFAULT 'done',   -- done | error
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (game_id)
);

CREATE INDEX IF NOT EXISTS idx_pgn_analysis_user ON public.pgn_analysis (user_id);

-- ── 3. BACKGROUND QUEUE: pgn_analysis_queue ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pgn_analysis_queue (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id      TEXT,
    user_id      TEXT,
    pgn          TEXT,
    fen          TEXT,
    depth        INTEGER DEFAULT 14,
    priority     INTEGER DEFAULT 0,
    status       TEXT DEFAULT 'queued',   -- queued | processing | done | error
    attempts     INTEGER DEFAULT 0,
    error        TEXT,
    requested_at TIMESTAMPTZ DEFAULT NOW(),
    started_at   TIMESTAMPTZ,
    finished_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pgn_queue_status ON public.pgn_analysis_queue (status, priority DESC, requested_at);

-- ── 4. ANNOTATIONS: pgn_notes ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pgn_notes (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id    TEXT REFERENCES public.pgn_games(id) ON DELETE CASCADE,
    user_id    TEXT,
    author     TEXT,           -- 'student' | 'coach' | 'tom-ai'
    ply        INTEGER,
    note       TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pgn_notes_game ON public.pgn_notes (game_id);

-- ── 5. AUTO-ENQUEUE: when a game is saved, queue it for analysis ─────────────
CREATE OR REPLACE FUNCTION public.fn_enqueue_pgn_analysis()
RETURNS TRIGGER AS $$
BEGIN
  IF (NEW.analysed IS DISTINCT FROM TRUE) THEN
    INSERT INTO public.pgn_analysis_queue (game_id, user_id, pgn, fen, depth, priority)
    VALUES (NEW.id, NEW.user_id, NEW.pgn, NEW.fen, 14,
            CASE WHEN NEW.source IN ('tournament','coach') THEN 5 ELSE 0 END)
    ON CONFLICT DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_enqueue_pgn_analysis ON public.pgn_games;
CREATE TRIGGER trg_enqueue_pgn_analysis
  AFTER INSERT ON public.pgn_games
  FOR EACH ROW EXECUTE FUNCTION public.fn_enqueue_pgn_analysis();

-- updated_at maintenance
CREATE OR REPLACE FUNCTION public.fn_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_touch_pgn_games ON public.pgn_games;
CREATE TRIGGER trg_touch_pgn_games
  BEFORE UPDATE ON public.pgn_games
  FOR EACH ROW EXECUTE FUNCTION public.fn_touch_updated_at();

-- ── 6. GRANTS (client-trust model, consistent with existing tables) ─────────
GRANT ALL ON TABLE public.pgn_games          TO anon, authenticated;
GRANT ALL ON TABLE public.pgn_analysis       TO anon, authenticated;
GRANT ALL ON TABLE public.pgn_analysis_queue TO anon, authenticated;
GRANT ALL ON TABLE public.pgn_notes          TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- ── 7. OPTIONAL: raw PGN blob storage bucket ────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('pgns', 'pgns', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "PGN Public Read"   ON storage.objects;
DROP POLICY IF EXISTS "PGN Allow Uploads" ON storage.objects;
DROP POLICY IF EXISTS "PGN Allow Deletes" ON storage.objects;
CREATE POLICY "PGN Public Read"   ON storage.objects FOR SELECT USING (bucket_id = 'pgns');
CREATE POLICY "PGN Allow Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'pgns');
CREATE POLICY "PGN Allow Deletes" ON storage.objects FOR DELETE USING (bucket_id = 'pgns');

-- Done. The edge function `analyze-pgn` consumes pgn_analysis_queue and writes
-- pgn_analysis rows (see supabase/functions/analyze-pgn/index.ts).
