-- ==============================================================================
-- ChessKidoo Academy — Complete Fresh Supabase Database Setup
-- ==============================================================================
-- TARGET:  https://bqlnsununvsyksvhczrm.supabase.co
-- VERSION: 3.0.0 (Full rebuild — all tables, indexes, seed data, storage)
--
-- INSTRUCTIONS:
-- 1. Open your Supabase Dashboard → SQL Editor
-- 2. Paste this ENTIRE script
-- 3. Click "Run" to build the complete schema from scratch
--
-- This script is IDEMPOTENT — safe to re-run. Uses IF NOT EXISTS / ON CONFLICT.
-- ==============================================================================


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 1: DROP ALL EXISTING TABLES (FRESH START)
-- ══════════════════════════════════════════════════════════════════════════════

DROP TABLE IF EXISTS public.hw_submissions CASCADE;
DROP TABLE IF EXISTS public.assignments CASCADE;
DROP TABLE IF EXISTS public.coach_attendance CASCADE;
DROP TABLE IF EXISTS public.puzzle_scores CASCADE;
DROP TABLE IF EXISTS public.monthly_reports CASCADE;
DROP TABLE IF EXISTS public.feedback CASCADE;
DROP TABLE IF EXISTS public.broadcasts CASCADE;
DROP TABLE IF EXISTS public.tournaments CASCADE;
DROP TABLE IF EXISTS public.batch_links CASCADE;
DROP TABLE IF EXISTS public.credentials CASCADE;
DROP TABLE IF EXISTS public.coach_notes CASCADE;
DROP TABLE IF EXISTS public.leads CASCADE;
DROP TABLE IF EXISTS public.meetings CASCADE;
DROP TABLE IF EXISTS public.resources CASCADE;
DROP TABLE IF EXISTS public."tourRatings" CASCADE;
DROP TABLE IF EXISTS public.ratings CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.document CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 2: CREATE ALL TABLES
-- ══════════════════════════════════════════════════════════════════════════════

-- ── 1. USERS TABLE ──────────────────────────────────────────────────────────
-- Core profile table for all users: admin, coach, student, parent
CREATE TABLE public.users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    userid          TEXT,
    email           TEXT,
    full_name       TEXT,
    role            TEXT,
    phone_number    TEXT,
    city            TEXT,
    level           TEXT,
    rating          INTEGER DEFAULT 800,
    coach           TEXT,
    batch           TEXT,
    session         TEXT,
    schedule        TEXT,
    fee             TEXT,
    status          TEXT,
    due_date        TEXT,
    join_date       TEXT,
    age             INTEGER,
    grade           TEXT,
    puzzle          INTEGER DEFAULT 0,
    game            INTEGER DEFAULT 0,
    star            INTEGER DEFAULT 0,
    photo           TEXT,
    certificate     TEXT,
    last_note       TEXT,
    "childEmail"    TEXT,
    timetable       TEXT,
    revenue         TEXT,
    classes         INTEGER DEFAULT 0,
    streak_count    INTEGER DEFAULT 0,
    streak_last_date TEXT,
    srs_data        JSONB,
    session_type    TEXT,
    payment_status  TEXT,
    -- Lichess integration
    lichess_username TEXT,
    lichess_games    INTEGER DEFAULT 0,
    lichess_blitz    INTEGER,
    lichess_bullet   INTEGER,
    lichess_title    TEXT,
    -- FIDE integration
    fide_id          TEXT,
    fide_rating      TEXT,
    fide_rapid       TEXT,
    fide_blitz       TEXT,
    fide_title       TEXT,
    fide_federation  TEXT,
    -- Payment tracking
    last_txn_id      TEXT,
    paid_date        TEXT,
    pay_method       TEXT,
    -- Availability (for coaches)
    availability     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 2. EXPENSES TABLE ──────────────────────────────────────────────────────
-- Admin-only: track academy expenses
CREATE TABLE public.expenses (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date        TEXT,
    category    TEXT,
    description TEXT,
    amount      TEXT,
    mode        TEXT,
    bill        TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 3. DOCUMENT TABLE ──────────────────────────────────────────────────────
-- File/document management for coaches and students
CREATE TABLE public.document (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_name   TEXT,
    name        TEXT,
    level       TEXT,
    coach       TEXT,
    link        TEXT,
    batch       TEXT,
    user_ids    TEXT,
    type        TEXT,
    notes       TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 4. ATTENDANCE TABLE ────────────────────────────────────────────────────
-- Student attendance tracking with unique constraint on user+date
CREATE TABLE public.attendance (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid          TEXT,
    "studentId"     TEXT,
    "studentName"   TEXT,
    "classId"       TEXT,
    "className"     TEXT,
    "coachId"       TEXT,
    "coachName"     TEXT,
    "markedAt"      TIMESTAMPTZ,
    date            TEXT,
    status          TEXT,
    class_title     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uq_attendance_user_date UNIQUE (userid, date)
);

-- ── 5. RATINGS TABLE ───────────────────────────────────────────────────────
-- Online/international rating history snapshots
CREATE TABLE public.ratings (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         TEXT,
    online          INTEGER,
    international   INTEGER,
    date            TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 6. TOURNAMENT RATINGS TABLE ────────────────────────────────────────────
-- Tournament results and rating changes
CREATE TABLE public."tourRatings" (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     TEXT,
    name        TEXT,
    result      TEXT,
    change      TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 7. RESOURCES TABLE ─────────────────────────────────────────────────────
-- Learning resources: videos, puzzles, documents
CREATE TABLE public.resources (
    id          TEXT PRIMARY KEY,
    name        TEXT,
    type        TEXT,
    level       TEXT,
    notes       TEXT,
    link        TEXT,
    coach       TEXT,
    batch       TEXT,
    fen         TEXT,
    solution    TEXT,
    difficulty  TEXT,
    category    TEXT,
    explanation TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 8. MEETINGS TABLE ──────────────────────────────────────────────────────
-- Scheduled class sessions and meetings
CREATE TABLE public.meetings (
    id              TEXT PRIMARY KEY,
    date            TEXT,
    time            TEXT,
    coach           TEXT,
    "coachId"       TEXT,
    "coachName"     TEXT,
    title           TEXT,
    batch           TEXT,
    duration        INTEGER,
    link            TEXT,
    notes           TEXT,
    type            TEXT,
    "studentIds"    TEXT[],
    status          TEXT,
    "liveStartedAt" TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 9. LEADS TABLE ─────────────────────────────────────────────────────────
-- Demo booking form submissions from the landing page
CREATE TABLE public.leads (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT,
    phone       TEXT,
    parent_name TEXT,
    child_age   TEXT,
    city        TEXT,
    status      TEXT,
    email       TEXT,
    message     TEXT,
    source      TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    full_name   TEXT,
    age         TEXT
);

-- ── 10. COACH NOTES TABLE ──────────────────────────────────────────────────
-- Coach-written notes/reviews about students
CREATE TABLE public.coach_notes (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student     TEXT,
    coach       TEXT,
    text        TEXT,
    date        TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 11. CREDENTIALS TABLE ──────────────────────────────────────────────────
-- Offline login fallback credentials (SHA-256 hashed passwords)
CREATE TABLE public.credentials (
    email       TEXT PRIMARY KEY,
    password    TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 12. BATCH LINKS TABLE ──────────────────────────────────────────────────
-- Google Meet / Zoom links per batch level
CREATE TABLE public.batch_links (
    batch_level TEXT PRIMARY KEY,
    link        TEXT,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 13. CLASSES TABLE ──────────────────────────────────────────────────────
-- Class definitions with schedule, students, and coach
CREATE TABLE public.classes (
    id              TEXT PRIMARY KEY,
    "coachId"       TEXT,
    "coachName"     TEXT,
    title           TEXT,
    level           TEXT,
    batch           TEXT,
    days            TEXT[],
    time            TEXT,
    duration        INTEGER,
    "zoomLink"      TEXT,
    max_students    INTEGER DEFAULT 10,
    "studentIds"    TEXT[],
    active          BOOLEAN DEFAULT true,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    students        INTEGER,
    max             INTEGER,
    coach           TEXT,
    schedule        TEXT
);

-- ── 14. MONTHLY REPORTS TABLE ──────────────────────────────────────────────
-- Monthly progress reports for students
CREATE TABLE public.monthly_reports (
    id              TEXT PRIMARY KEY,
    "studentId"     TEXT,
    "studentName"   TEXT,
    "coachId"       TEXT,
    "coachName"     TEXT,
    month           INTEGER,
    year            INTEGER,
    attendance      INTEGER,
    puzzles         INTEGER,
    notes           TEXT,
    recommendation  TEXT,
    topics          TEXT[],
    rating          INTEGER,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 15. PUZZLE SCORES TABLE ────────────────────────────────────────────────
-- Individual puzzle attempt results for gamification
CREATE TABLE public.puzzle_scores (
    id          TEXT PRIMARY KEY,
    "userId"    TEXT,
    "userName"  TEXT,
    "puzzleId"  TEXT,
    solved      BOOLEAN,
    time        INTEGER,
    mistakes    INTEGER,
    xp          INTEGER,
    date        TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 16. COACH ATTENDANCE TABLE ─────────────────────────────────────────────
-- Tracks when coaches join their classes
CREATE TABLE public.coach_attendance (
    id          TEXT PRIMARY KEY,
    "coachId"   TEXT,
    "classId"   TEXT,
    date        TEXT,
    "joinedAt"  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 17. ASSIGNMENTS TABLE ──────────────────────────────────────────────────
-- Homework assignments (PGN-based chess problems)
CREATE TABLE public.assignments (
    id              TEXT PRIMARY KEY,
    title           TEXT,
    pgn             TEXT,
    type            TEXT,
    "assignedTo"    TEXT[],
    "dueDate"       TEXT,
    description     TEXT,
    coach           TEXT,
    moves           JSONB,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 18. HW SUBMISSIONS TABLE ──────────────────────────────────────────────
-- Student homework submission results
CREATE TABLE public.hw_submissions (
    id              TEXT PRIMARY KEY,
    assignment_id   TEXT,
    student_id      TEXT,
    accuracy        INTEGER,
    "movesStudied"  INTEGER,
    "totalMoves"    INTEGER,
    note            TEXT,
    completed       BOOLEAN DEFAULT false,
    "submittedAt"   TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 19. FEEDBACK TABLE ─────────────────────────────────────────────────────
-- User feedback/reviews between coaches, students, parents
CREATE TABLE public.feedback (
    id          TEXT PRIMARY KEY,
    "fromId"    TEXT,
    "fromName"  TEXT,
    "fromRole"  TEXT,
    "childId"   TEXT,
    "childName" TEXT,
    "toId"      TEXT,
    "toName"    TEXT,
    message     TEXT,
    rating      INTEGER,
    category    TEXT,
    replied     BOOLEAN DEFAULT false,
    reply       TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 20. BROADCASTS TABLE ──────────────────────────────────────────────────
-- Live chessboard broadcast state (coach streams to students)
CREATE TABLE public.broadcasts (
    id          TEXT PRIMARY KEY,
    fen         TEXT,
    pgn         TEXT,
    coach       TEXT,
    ts          BIGINT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 21. TOURNAMENTS TABLE ──────────────────────────────────────────────────
-- Internal academy tournaments (referenced in db.js but was missing from schema!)
CREATE TABLE public.tournaments (
    id              TEXT PRIMARY KEY,
    title           TEXT,
    type            TEXT,
    status          TEXT DEFAULT 'upcoming',
    rounds          INTEGER DEFAULT 5,
    "timeControl"   TEXT DEFAULT '10+0',
    participants    JSONB DEFAULT '[]'::jsonb,
    pairings        JSONB DEFAULT '[]'::jsonb,
    standings       JSONB DEFAULT '[]'::jsonb,
    results         JSONB DEFAULT '[]'::jsonb,
    "currentRound"  INTEGER DEFAULT 0,
    "startDate"     TEXT,
    "endDate"       TEXT,
    "createdBy"     TEXT,
    "createdAt"     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 3: INDEXES FOR PERFORMANCE
-- ══════════════════════════════════════════════════════════════════════════════

-- Users
CREATE INDEX IF NOT EXISTS idx_users_role     ON public.users(role);
CREATE INDEX IF NOT EXISTS idx_users_coach    ON public.users(coach);
CREATE INDEX IF NOT EXISTS idx_users_email    ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_batch    ON public.users(batch);
CREATE INDEX IF NOT EXISTS idx_users_level    ON public.users(level);
CREATE INDEX IF NOT EXISTS idx_users_lichess  ON public.users(lichess_username);
CREATE INDEX IF NOT EXISTS idx_users_fide     ON public.users(fide_id);

-- Attendance
CREATE INDEX IF NOT EXISTS idx_attendance_userid   ON public.attendance(userid);
CREATE INDEX IF NOT EXISTS idx_attendance_date     ON public.attendance(date);
CREATE INDEX IF NOT EXISTS idx_attendance_classid  ON public.attendance("classId");
CREATE INDEX IF NOT EXISTS idx_attendance_coachid  ON public.attendance("coachId");
CREATE INDEX IF NOT EXISTS idx_attendance_status   ON public.attendance(status);

-- Ratings
CREATE INDEX IF NOT EXISTS idx_ratings_user_id ON public.ratings(user_id);
CREATE INDEX IF NOT EXISTS idx_ratings_date    ON public.ratings(date);

-- Tour Ratings
CREATE INDEX IF NOT EXISTS idx_tourratings_user_id ON public."tourRatings"(user_id);

-- Meetings
CREATE INDEX IF NOT EXISTS idx_meetings_date   ON public.meetings(date);
CREATE INDEX IF NOT EXISTS idx_meetings_coach  ON public.meetings(coach);
CREATE INDEX IF NOT EXISTS idx_meetings_status ON public.meetings(status);

-- Classes
CREATE INDEX IF NOT EXISTS idx_classes_coachid ON public.classes("coachId");
CREATE INDEX IF NOT EXISTS idx_classes_level   ON public.classes(level);
CREATE INDEX IF NOT EXISTS idx_classes_batch   ON public.classes(batch);
CREATE INDEX IF NOT EXISTS idx_classes_active  ON public.classes(active);

-- Monthly Reports
CREATE INDEX IF NOT EXISTS idx_reports_student    ON public.monthly_reports("studentId");
CREATE INDEX IF NOT EXISTS idx_reports_month_year ON public.monthly_reports(month, year);
CREATE INDEX IF NOT EXISTS idx_reports_coachid    ON public.monthly_reports("coachId");

-- Puzzle Scores
CREATE INDEX IF NOT EXISTS idx_puzzle_scores_userid ON public.puzzle_scores("userId");
CREATE INDEX IF NOT EXISTS idx_puzzle_scores_date   ON public.puzzle_scores(date);

-- Coach Attendance
CREATE INDEX IF NOT EXISTS idx_coach_att_coachid ON public.coach_attendance("coachId");
CREATE INDEX IF NOT EXISTS idx_coach_att_date    ON public.coach_attendance(date);

-- Assignments
CREATE INDEX IF NOT EXISTS idx_assignments_coach ON public.assignments(coach);

-- HW Submissions
CREATE INDEX IF NOT EXISTS idx_hw_assignment  ON public.hw_submissions(assignment_id);
CREATE INDEX IF NOT EXISTS idx_hw_student     ON public.hw_submissions(student_id);

-- Feedback
CREATE INDEX IF NOT EXISTS idx_feedback_fromid ON public.feedback("fromId");
CREATE INDEX IF NOT EXISTS idx_feedback_toid   ON public.feedback("toId");

-- Leads
CREATE INDEX IF NOT EXISTS idx_leads_status ON public.leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_email  ON public.leads(email);

-- Coach Notes
CREATE INDEX IF NOT EXISTS idx_coach_notes_student ON public.coach_notes(student);
CREATE INDEX IF NOT EXISTS idx_coach_notes_coach   ON public.coach_notes(coach);

-- Resources
CREATE INDEX IF NOT EXISTS idx_resources_type  ON public.resources(type);
CREATE INDEX IF NOT EXISTS idx_resources_level ON public.resources(level);
CREATE INDEX IF NOT EXISTS idx_resources_batch ON public.resources(batch);

-- Documents
CREATE INDEX IF NOT EXISTS idx_document_level ON public.document(level);
CREATE INDEX IF NOT EXISTS idx_document_coach ON public.document(coach);
CREATE INDEX IF NOT EXISTS idx_document_batch ON public.document(batch);

-- Tournaments
CREATE INDEX IF NOT EXISTS idx_tournaments_status ON public.tournaments(status);


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 4: HELPER FUNCTIONS
-- ══════════════════════════════════════════════════════════════════════════════

-- Auto-update updated_at trigger function
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- RLS Helper: extract role from JWT custom claim
CREATE OR REPLACE FUNCTION public.current_role_claim()
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT COALESCE(
    (auth.jwt() -> 'app_metadata' ->> 'role'),
    ''
  );
$$;

-- RLS Helper: check if current user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT current_role_claim() = 'admin';
$$;


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 5: DATABASE SECURITY & API ACCESS
-- ══════════════════════════════════════════════════════════════════════════════
-- For initial setup / development, RLS is DISABLED to allow the frontend
-- (which uses the anon key) to read/write freely.
--
-- ⚠️  BEFORE GOING TO PRODUCTION: Enable RLS and apply the policies
--     from supabase/rls.sql for proper security.
-- ══════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.document DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."tourRatings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.batch_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.puzzle_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.hw_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcasts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournaments DISABLE ROW LEVEL SECURITY;

-- Grant full access to both anon and authenticated roles
GRANT ALL ON TABLE public.users TO anon, authenticated;
GRANT ALL ON TABLE public.expenses TO anon, authenticated;
GRANT ALL ON TABLE public.document TO anon, authenticated;
GRANT ALL ON TABLE public.attendance TO anon, authenticated;
GRANT ALL ON TABLE public.ratings TO anon, authenticated;
GRANT ALL ON TABLE public."tourRatings" TO anon, authenticated;
GRANT ALL ON TABLE public.resources TO anon, authenticated;
GRANT ALL ON TABLE public.meetings TO anon, authenticated;
GRANT ALL ON TABLE public.leads TO anon, authenticated;
GRANT ALL ON TABLE public.coach_notes TO anon, authenticated;
GRANT ALL ON TABLE public.credentials TO anon, authenticated;
GRANT ALL ON TABLE public.batch_links TO anon, authenticated;
GRANT ALL ON TABLE public.classes TO anon, authenticated;
GRANT ALL ON TABLE public.monthly_reports TO anon, authenticated;
GRANT ALL ON TABLE public.puzzle_scores TO anon, authenticated;
GRANT ALL ON TABLE public.coach_attendance TO anon, authenticated;
GRANT ALL ON TABLE public.assignments TO anon, authenticated;
GRANT ALL ON TABLE public.hw_submissions TO anon, authenticated;
GRANT ALL ON TABLE public.feedback TO anon, authenticated;
GRANT ALL ON TABLE public.broadcasts TO anon, authenticated;
GRANT ALL ON TABLE public.tournaments TO anon, authenticated;

-- Grant sequence usage for auto-generated IDs
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 6: STORAGE BUCKETS
-- ══════════════════════════════════════════════════════════════════════════════

-- Documents bucket (for file uploads: PDFs, images, etc.)
INSERT INTO storage.buckets (id, name, public)
VALUES ('documents', 'documents', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Allow Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow Deletes" ON storage.objects;
DROP POLICY IF EXISTS "Allow Updates" ON storage.objects;

-- Storage policies: public read, authenticated upload/delete
CREATE POLICY "Public Access"  ON storage.objects FOR SELECT USING (bucket_id = 'documents');
CREATE POLICY "Allow Uploads"  ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'documents');
CREATE POLICY "Allow Deletes"  ON storage.objects FOR DELETE USING (bucket_id = 'documents');
CREATE POLICY "Allow Updates"  ON storage.objects FOR UPDATE USING (bucket_id = 'documents');

-- Photos bucket (for user profile photos and certificates)
INSERT INTO storage.buckets (id, name, public)
VALUES ('photos', 'photos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Photos storage policies
DROP POLICY IF EXISTS "Photos Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Photos Allow Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Photos Allow Deletes" ON storage.objects;

CREATE POLICY "Photos Public Access"  ON storage.objects FOR SELECT USING (bucket_id = 'photos');
CREATE POLICY "Photos Allow Uploads"  ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'photos');
CREATE POLICY "Photos Allow Deletes"  ON storage.objects FOR DELETE USING (bucket_id = 'photos');


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 7: SEED DATA
-- ══════════════════════════════════════════════════════════════════════════════

-- ── Admin User ────────────────────────────────────────────────────────────────
INSERT INTO public.users (id, userid, email, full_name, role, rating, classes, created_at)
VALUES
  ('a0000000-0000-4000-8000-000000000001', 'admin-root', 'admin@chesskidoo.com', 'Academy Admin', 'admin', NULL, 0, NOW())
ON CONFLICT (id) DO NOTHING;

-- ── Coaches ──────────────────────────────────────────────────────────────────
INSERT INTO public.users (id, userid, email, full_name, role, rating, classes, coach, timetable, created_at)
VALUES
  ('c0c0c0c0-0001-4000-8000-000000000001', 'c_arivuselevam', 'arivuselvam@chesskidoo.com', 'ARIVUSELVAM', 'coach', 1500, 0, 'ARIVUSELVAM', 'Mon-Sat 17:00', NOW()),
  ('c0c0c0c0-0002-4000-8000-000000000002', 'c_vishnu',       'vishnu@chesskidoo.com',      'VISHNU',       'coach', 1600, 0, 'VISHNU',       'Fri-Sat 4PM-8PM', NOW()),
  ('c0c0c0c0-0003-4000-8000-000000000003', 'c_gyanasurya',   'gyanasurya@chesskidoo.com',  'GYANASURYA',   'coach', 1550, 0, 'GYANASURYA',   'Tue-Fri 6PM, Weekend', NOW()),
  ('c0c0c0c0-0004-4000-8000-000000000004', 'c_yogesh',       'yogesh@chesskidoo.com',      'YOGESH',       'coach', 1620, 0, 'YOGESH',       'Weekend', NOW()),
  ('c0c0c0c0-0005-4000-8000-000000000005', 'c_haris',        'haris@chesskidoo.com',       'HARIS',        'coach', 1500, 0, 'HARIS',        'Sat-Sun 9AM & 5PM', NOW()),
  ('c0c0c0c0-0006-4000-8000-000000000006', 'c_rohit',        'rohit@chesskidoo.com',       'ROHIT',        'coach', 1500, 0, 'ROHIT',        'Mon-Fri 5PM', NOW()),
  ('c0c0c0c0-0007-4000-8000-000000000007', 'c_sudhin',       'sudhin@chesskidoo.com',      'SUDHIN',       'coach', 1450, 0, 'SUDHIN',       'Mon-Wed 5PM', NOW()),
  ('c0c0c0c0-0008-4000-8000-000000000008', 'c_ranjith',      'ranjith@chesskidoo.com',     'RANJITH',      'coach', 1700, 0, 'RANJITH',      'Thu-Sun 5PM', NOW())
ON CONFLICT (id) DO NOTHING;

-- ── Sample Students ──────────────────────────────────────────────────────────
INSERT INTO public.users
  (id, email, full_name, role, level, rating, coach, batch, session, schedule, fee, status, due_date, join_date)
VALUES
  ('a1a1a1a1-0001-4000-8000-000000000001', 'aadhavan@chesskidoo.com',  'AADHAVAN - SINGAPORE', 'student', 'Beginner',     850,  'ARIVUSELVAM', 'Evening',  'Group', '17:00',           '2200', 'Paid',    '04-May-2026', '2026-04-20'),
  ('a1a1a1a1-0002-4000-8000-000000000002', 'aarav@chesskidoo.com',     'AARA V',               'student', 'Beginner',     800,  'GYANASURYA',  'Weekend',  'Group', 'WEEKEND',         '1800', 'Paid',    '14-May-2026', '2026-04-24'),
  ('a1a1a1a1-0003-4000-8000-000000000003', 'anfal@chesskidoo.com',     'ANFAL',                'student', 'Intermediate', 800,  'VISHNU',      'Evening',  'Group', 'FRI & SAT',       '3300', 'Paid',    '20-May-2026', '2026-04-24'),
  ('a1a1a1a1-0004-4000-8000-000000000004', 'anushya@chesskidoo.com',   'ANUSHYA',              'student', 'Beginner',     800,  'ARIVUSELVAM', 'Evening',  'Group', '17:00',           '1800', 'Pending', '18-May-2026', '2026-04-23'),
  ('a1a1a1a1-0005-4000-8000-000000000005', 'anyush@chesskidoo.com',    'ANYUSH',               'student', 'Intermediate', 800,  'GYANASURYA',  'Evening',  'Group', '17:00',           '1000', 'Pending', '18-May-2026', '2026-04-23'),
  ('a1a1a1a1-0006-4000-8000-000000000006', 'arunya@chesskidoo.com',    'ARUNYA',               'student', 'Beginner',     800,  'HARIS',       'Weekend',  'Group', 'Weekend',         '2400', 'Pending', '24-May-2026', '2026-04-24'),
  ('a1a1a1a1-0007-4000-8000-000000000007', 'athivik@chesskidoo.com',   'ATHIVIK',              'student', 'Beginner',     800,  'YOGESH',      'Weekend',  'Group', 'WEEKEND SUN&MON', '2500', 'Paid',    '12-May-2026', '2026-04-24'),
  ('a1a1a1a1-0008-4000-8000-000000000008', 'atish@chesskidoo.com',     'ATISH VIDUN',          'student', 'Beginner',     800,  'ARIVUSELVAM', 'Weekend',  'Group', 'WEEKEND',         '3200', 'Paid',    '04-May-2026', '2026-04-24'),
  ('a1a1a1a1-0009-4000-8000-000000000009', 'balaji@chesskidoo.com',    'BALAJI GANESH',        'student', 'Beginner',     800,  'GYANASURYA',  'Weekday',  'Group', 'WEEKDAY',         '5200', 'Paid',    '05-May-2026', '2026-02-21'),
  ('a1a1a1a1-0010-4000-8000-000000000010', 'faithma@chesskidoo.com',   'Faithma',              'student', 'Beginner',     800,  'YOGESH',      'Evening',  'Group', '17:00',           '1200', 'Pending', '14-May-2026', '2026-04-14'),
  ('a1a1a1a1-0011-4000-8000-000000000011', 'jayaraj@chesskidoo.com',   'JAYARAJ',              'student', 'Beginner',     1000, 'VISHNU',      'Evening',  'Group', 'Fri & Sat',       '2500', 'Pending', '20-May-2026', '2026-03-07')
ON CONFLICT (id) DO NOTHING;

-- ── Default Offline Credentials (SHA-256 hashed) ─────────────────────────────
-- admin@chesskidoo.com / admin123
-- coaches / chess123
INSERT INTO public.credentials (email, password, created_at)
VALUES
  ('admin@chesskidoo.com',       '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', NOW()),
  ('admin@gmail.com',            '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', NOW()),
  ('arivuselvam@chesskidoo.com', '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('vishnu@chesskidoo.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('gyanasurya@chesskidoo.com',  '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('yogesh@chesskidoo.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('haris@chesskidoo.com',       '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('rohit@chesskidoo.com',       '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('sudhin@chesskidoo.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW()),
  ('ranjith@chesskidoo.com',     '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55', NOW())
ON CONFLICT (email) DO NOTHING;

-- ── Default Batch Links ──────────────────────────────────────────────────────
INSERT INTO public.batch_links (batch_level, link, updated_at)
VALUES
  ('Beginner',     'https://meet.google.com/beg-inner-room', NOW()),
  ('Intermediate', 'https://meet.google.com/int-strategy-abc', NOW()),
  ('Advanced',     'https://meet.google.com/adv-endgames-xyz', NOW())
ON CONFLICT (batch_level) DO NOTHING;


-- ══════════════════════════════════════════════════════════════════════════════
-- PHASE 8: REALTIME CONFIGURATION
-- ══════════════════════════════════════════════════════════════════════════════
-- Enable realtime for tables that need live updates

-- Broadcasts need realtime for live chess board streaming
ALTER PUBLICATION supabase_realtime ADD TABLE public.broadcasts;

-- Attendance for live attendance tracking
ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance;

-- Meetings for live class status updates
ALTER PUBLICATION supabase_realtime ADD TABLE public.meetings;

-- Tournaments for live tournament bracket updates
ALTER PUBLICATION supabase_realtime ADD TABLE public.tournaments;


-- ══════════════════════════════════════════════════════════════════════════════
-- ✅ SETUP COMPLETE
-- ══════════════════════════════════════════════════════════════════════════════
-- Tables created:  21
-- Indexes created: 38
-- Storage buckets: 2 (documents, photos)
-- Seed data:       Admin + 8 coaches + 11 students + credentials + batch links
-- Realtime:        broadcasts, attendance, meetings, tournaments
--
-- NEXT STEPS:
-- 1. Run this SQL in Supabase Dashboard → SQL Editor
-- 2. Verify tables in Table Editor
-- 3. Update .env.local with the new project URL and anon key
-- 4. For production: run supabase/rls.sql to enable Row Level Security
-- ══════════════════════════════════════════════════════════════════════════════
