-- =============================================================================
-- ChessKidoo — DEFINITIVE Supabase Setup Script  (v4 — reconciled with code)
-- =============================================================================
-- WHAT THIS FIXES:
--   The app's JavaScript sends column names like "maxStudents", "zoomLink",
--   "coachName", "createdAt". The old schema used max_students / zoomlink /
--   created_at, so Supabase rejected every write and the app silently fell
--   back to localStorage demo data. This script rebuilds every table so the
--   columns EXACTLY match what assets/js/*.js sends — making real persistence
--   work across all 4 portals.
--
-- HOW TO RUN:
--   1. Open Supabase Dashboard -> your project (hcjuyqicftkgpiyrkscr)
--   2. Left sidebar -> SQL Editor -> New query
--   3. Paste this ENTIRE file, click "Run"
--   4. It is safe to re-run; it rebuilds cleanly each time.
--
-- WARNING: The DROP block below WIPES existing table data. That is intended
--   for a pre-launch clean build. If you already have real data you want to
--   keep, comment out the DROP block before running.
-- =============================================================================

-- ── DROP (clean rebuild) ─────────────────────────────────────────────────────
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.document CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.ratings CASCADE;
DROP TABLE IF EXISTS public."tourRatings" CASCADE;
DROP TABLE IF EXISTS public.tourratings CASCADE;
DROP TABLE IF EXISTS public.resources CASCADE;
DROP TABLE IF EXISTS public.meetings CASCADE;
DROP TABLE IF EXISTS public.leads CASCADE;
DROP TABLE IF EXISTS public.coach_notes CASCADE;
DROP TABLE IF EXISTS public.credentials CASCADE;
DROP TABLE IF EXISTS public.batch_links CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.monthly_reports CASCADE;
DROP TABLE IF EXISTS public.puzzle_scores CASCADE;
DROP TABLE IF EXISTS public.coach_attendance CASCADE;
DROP TABLE IF EXISTS public.assignments CASCADE;
DROP TABLE IF EXISTS public.hw_submissions CASCADE;
DROP TABLE IF EXISTS public.feedback CASCADE;
DROP TABLE IF EXISTS public.broadcasts CASCADE;

-- ── 1. USERS ─────────────────────────────────────────────────────────────────
-- id is TEXT (not UUID) so it accepts BOTH Supabase Auth UUIDs AND the
-- string ids the app generates (e.g. 'student-123', 'par-abc', 's1').
CREATE TABLE public.users (
    id              TEXT PRIMARY KEY,
    userid          TEXT,
    email           TEXT,
    full_name       TEXT,
    role            TEXT,
    phone_number    TEXT,
    city            TEXT,
    level           TEXT,
    rating          INTEGER DEFAULT 800,
    coach           TEXT,
    batch           TEXT,
    session         TEXT,
    schedule        TEXT,
    fee             TEXT,
    status          TEXT,
    due_date        TEXT,
    join_date       TEXT,
    age             INTEGER,
    grade           TEXT,
    puzzle          INTEGER DEFAULT 0,
    game            INTEGER DEFAULT 0,
    star            INTEGER DEFAULT 0,
    photo           TEXT,
    certificate     TEXT,
    last_note       TEXT,
    "childEmail"    TEXT,
    "childId"       TEXT,
    child_id        TEXT,
    timetable       TEXT,
    revenue         TEXT,
    classes         INTEGER DEFAULT 0,
    streak_count    INTEGER DEFAULT 0,
    streak_last_date TEXT,
    srs_data        JSONB,
    auth_id         TEXT,
    fide_rating     TEXT,
    session_type    TEXT,
    payment_status  TEXT,
    xp              INTEGER DEFAULT 0,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. EXPENSES ──────────────────────────────────────────────────────────────
CREATE TABLE public.expenses (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date        TEXT,
    category    TEXT,
    description TEXT,
    amount      TEXT,
    mode        TEXT,
    bill        TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. DOCUMENT (homework / class materials) ─────────────────────────────────
CREATE TABLE public.document (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_name   TEXT,
    name        TEXT,
    level       TEXT,
    coach       TEXT,
    link        TEXT,
    batch       TEXT,
    user_ids    TEXT,
    type        TEXT,
    notes       TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 4. ATTENDANCE ────────────────────────────────────────────────────────────
-- id is TEXT (classes-system.js sends a string id; admin/coach send a number).
CREATE TABLE public.attendance (
    id            TEXT PRIMARY KEY DEFAULT (extract(epoch from now())*1000)::bigint::text,
    userid        TEXT,
    "studentId"   TEXT,
    "studentName" TEXT,
    "classId"     TEXT,
    "className"   TEXT,
    "coachId"     TEXT,
    "coachName"   TEXT,
    "markedAt"    TIMESTAMPTZ,
    date          TEXT,
    status        TEXT,
    class_title   TEXT,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_attendance_user_date UNIQUE (userid, date)
);

-- ── 5. RATINGS ───────────────────────────────────────────────────────────────
CREATE TABLE public.ratings (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id       TEXT,
    online        INTEGER,
    international INTEGER,
    date          TIMESTAMPTZ DEFAULT NOW()
);

-- ── 6. TOUR RATINGS ──────────────────────────────────────────────────────────
-- Quoted name so the code's .from('tourRatings') resolves correctly.
CREATE TABLE public."tourRatings" (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    TEXT,
    name       TEXT,
    result     TEXT,
    change     TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 7. RESOURCES (puzzles / coach uploads) ───────────────────────────────────
CREATE TABLE public.resources (
    id          TEXT PRIMARY KEY,
    name        TEXT,
    type        TEXT,
    level       TEXT,
    notes       TEXT,
    link        TEXT,
    coach       TEXT,
    batch       TEXT,
    fen         TEXT,
    solution    TEXT,
    difficulty  TEXT,
    category    TEXT,
    explanation TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 8. MEETINGS ──────────────────────────────────────────────────────────────
CREATE TABLE public.meetings (
    id           TEXT PRIMARY KEY,
    date         TEXT,
    time         TEXT,
    coach        TEXT,
    "coachId"    TEXT,
    "coachName"  TEXT,
    title        TEXT,
    batch        TEXT,
    duration     INTEGER,
    link         TEXT,
    notes        TEXT,
    type         TEXT,
    "studentIds" TEXT[],
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── 9. LEADS (demo bookings / contact form) ──────────────────────────────────
CREATE TABLE public.leads (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT,
    phone       TEXT,
    parent_name TEXT,
    child_age   TEXT,
    city        TEXT,
    status      TEXT,
    email       TEXT,
    message     TEXT,
    source      TEXT,
    full_name   TEXT,
    age         TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 10. COACH NOTES (student reviews) ────────────────────────────────────────
CREATE TABLE public.coach_notes (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student    TEXT,
    coach      TEXT,
    text       TEXT,
    date       TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 11. CREDENTIALS (per-user login passwords, SHA-256) ──────────────────────
CREATE TABLE public.credentials (
    email      TEXT PRIMARY KEY,
    password   TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 12. BATCH LINKS (Google Meet rooms per level) ────────────────────────────
CREATE TABLE public.batch_links (
    batch_level TEXT PRIMARY KEY,
    link        TEXT,
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 13. CLASSES ──────────────────────────────────────────────────────────────
-- Columns match classes-system.js / admin.js EXACTLY (camelCase quoted).
CREATE TABLE public.classes (
    id           TEXT PRIMARY KEY,
    "coachId"    TEXT,
    "coachName"  TEXT,
    title        TEXT,
    level        TEXT,
    batch        TEXT,
    days         TEXT[],
    time         TEXT,
    duration     INTEGER,
    "zoomLink"   TEXT,
    "maxStudents" INTEGER DEFAULT 10,
    "studentIds" TEXT[],
    active       BOOLEAN DEFAULT true,
    "createdAt"  TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── 14. MONTHLY / WEEKLY REPORTS ─────────────────────────────────────────────
-- topics is TEXT (the form sends a comma string, not an array).
CREATE TABLE public.monthly_reports (
    id             TEXT PRIMARY KEY,
    "studentId"    TEXT,
    "studentName"  TEXT,
    "coachId"      TEXT,
    "coachName"    TEXT,
    month          INTEGER,
    year           INTEGER,
    attendance     INTEGER,
    puzzles        INTEGER,
    notes          TEXT,
    recommendation TEXT,
    topics         TEXT,
    rating         INTEGER,
    type           TEXT,
    data           JSONB,
    "createdAt"    TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ── 15. PUZZLE SCORES ────────────────────────────────────────────────────────
CREATE TABLE public.puzzle_scores (
    id          TEXT PRIMARY KEY,
    "userId"    TEXT,
    "userName"  TEXT,
    "puzzleId"  TEXT,
    solved      BOOLEAN,
    time        INTEGER,
    mistakes    INTEGER,
    xp          INTEGER,
    date        TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 16. COACH ATTENDANCE ─────────────────────────────────────────────────────
CREATE TABLE public.coach_attendance (
    id         TEXT PRIMARY KEY,
    "coachId"  TEXT,
    "classId"  TEXT,
    date       TEXT,
    "joinedAt" TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 17. ASSIGNMENTS (homework) ───────────────────────────────────────────────
CREATE TABLE public.assignments (
    id           TEXT PRIMARY KEY,
    title        TEXT,
    pgn          TEXT,
    type         TEXT,
    "assignedTo" TEXT[],
    "dueDate"    TEXT,
    description  TEXT,
    coach        TEXT,
    moves        JSONB,
    created      BIGINT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── 18. HOMEWORK SUBMISSIONS ─────────────────────────────────────────────────
CREATE TABLE public.hw_submissions (
    id            TEXT PRIMARY KEY,
    assignment_id TEXT,
    student_id    TEXT,
    accuracy      INTEGER,
    "movesStudied" INTEGER,
    "totalMoves"  INTEGER,
    note          TEXT,
    completed     BOOLEAN DEFAULT false,
    "submittedAt" TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── 19. FEEDBACK (parent + coach) ────────────────────────────────────────────
-- Superset of both feedback shapes used in the code so no write is rejected.
CREATE TABLE public.feedback (
    id            TEXT PRIMARY KEY,
    "fromId"      TEXT,
    "fromName"    TEXT,
    "fromRole"    TEXT,
    "childId"     TEXT,
    "childName"   TEXT,
    "toId"        TEXT,
    "toName"      TEXT,
    message       TEXT,
    rating        INTEGER,
    category      TEXT,
    replied       BOOLEAN DEFAULT false,
    reply         TEXT,
    parent_name   TEXT,
    parent_email  TEXT,
    student_email TEXT,
    text          TEXT,
    status        TEXT,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── 20. BROADCASTS (live classroom position) ─────────────────────────────────
CREATE TABLE public.broadcasts (
    id         TEXT PRIMARY KEY,
    fen        TEXT,
    pgn        TEXT,
    coach      TEXT,
    ts         BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- ACCESS — disable RLS + grant the anon/authenticated API roles full access.
-- The app uses the public anon key directly; RLS is intentionally off here.
-- (For a hardened post-launch setup, see the note in LAUNCH_CHECKLIST.md.)
-- =============================================================================
DO $$
DECLARE t TEXT;
BEGIN
  FOR t IN
    SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('ALTER TABLE public.%I DISABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('GRANT ALL ON public.%I TO anon, authenticated;', t);
  END LOOP;
END $$;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- =============================================================================
-- STORAGE — bucket for homework / material file uploads
-- =============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('documents', 'documents', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "ck_docs_read"   ON storage.objects;
DROP POLICY IF EXISTS "ck_docs_write"  ON storage.objects;
DROP POLICY IF EXISTS "ck_docs_delete" ON storage.objects;
CREATE POLICY "ck_docs_read"   ON storage.objects FOR SELECT USING (bucket_id = 'documents');
CREATE POLICY "ck_docs_write"  ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'documents');
CREATE POLICY "ck_docs_delete" ON storage.objects FOR DELETE USING (bucket_id = 'documents');

-- =============================================================================
-- SEED DATA — admin, coaches, demo logins
-- =============================================================================

-- Admin + 8 coaches (emails match the app's default credential list)
INSERT INTO public.users (id, userid, email, full_name, role, rating, level) VALUES
  ('a007b0b0-9b30-478f-a147-1af18dff20ce', 'admin', 'admin@gmail.com',       'Academy Admin',   'admin', NULL, NULL),
  ('c0c0c0c0-0000-4000-8000-000000000001', 'c1', 'arivuselvam@gmail.com', 'ARIVUSELVAM',     'coach', 1500, 'Advanced'),
  ('c0c0c0c0-0000-4000-8000-000000000002', 'c2', 'gyanasurya@gmail.com',  'GYANASURYA',      'coach', 1450, 'Intermediate'),
  ('c0c0c0c0-0000-4000-8000-000000000003', 'c3', 'vishnu@gmail.com',      'VISHNU',          'coach', 1600, 'Advanced'),
  ('c0c0c0c0-0000-4000-8000-000000000004', 'c4', 'haris@gmail.com',       'HARIS',           'coach', 1300, 'Beginner'),
  ('c0c0c0c0-0000-4000-8000-000000000005', 'c5', 'yogesh@gmail.com',      'YOGESH',          'coach', 1350, 'Beginner'),
  ('c0c0c0c0-0000-4000-8000-000000000006', 'c6', 'sudhin@gmail.com',      'SUDHIN',          'coach', 1300, 'Beginner'),
  ('c0c0c0c0-0000-4000-8000-000000000007', 'c7', 'ranjith@gmail.com',     'RANJITH',         'coach', 1700, 'Advanced'),
  ('c0c0c0c0-0000-4000-8000-000000000008', 'c8', 'rohith@gmail.com',      'ROHITH SELVARAJ', 'coach', 1400, 'Beginner')
ON CONFLICT (id) DO NOTHING;

-- One demo student so the student portal has a working login out of the box
INSERT INTO public.users (id, userid, email, full_name, role, level, rating, coach, batch, status) VALUES
  ('student-uuid-emma', '101', 'student@gmail.com', 'Emma Wilson', 'student', 'Intermediate', 800, 'ARIVUSELVAM', 'Evening', 'Paid')
ON CONFLICT (id) DO NOTHING;

-- Login credentials (SHA-256 hashed).  admin password = admin123 ; others = chess123
INSERT INTO public.credentials (email, password) VALUES
  ('admin@gmail.com',       '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'),
  ('student@gmail.com',     '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('arivuselvam@gmail.com', '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('gyanasurya@gmail.com',  '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('vishnu@gmail.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('haris@gmail.com',       '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('yogesh@gmail.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('sudhin@gmail.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('ranjith@gmail.com',     '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55'),
  ('rohith@gmail.com',      '777a025f5ca4a20f7bafee940f2820e28e1f4bbcbd9dd774bbce883166ef7c55')
ON CONFLICT (email) DO NOTHING;

-- Default Google Meet links per level
INSERT INTO public.batch_links (batch_level, link) VALUES
  ('Beginner',     'https://meet.google.com/beg-inner-room'),
  ('Intermediate', 'https://meet.google.com/int-strategy-abc'),
  ('Advanced',     'https://meet.google.com/adv-endgames-xyz')
ON CONFLICT (batch_level) DO NOTHING;

-- =============================================================================
-- DONE.  All 20 tables now match the column names the app sends.
-- Verify: SELECT table_name FROM information_schema.tables WHERE table_schema='public';
-- =============================================================================
